# Generated by Django 5.1.1 on 2024-09-17 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitokuApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Sin Especialidad', max_length=30, verbose_name='Nombre de la Especialidad')),
                ('institucion', models.CharField(max_length=30, verbose_name='Institución')),
                ('anio_recebimiento', models.DateField(verbose_name='Año de Recebimiento')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'db_table': 'especialidad',
            },
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_paterno', models.CharField(max_length=20, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=20, verbose_name='Apellido Materno')),
                ('nombres', models.CharField(max_length=20, verbose_name='Nombres')),
                ('telefonoDoctor', models.IntegerField(verbose_name='Teléfono')),
                ('emailDoctor', models.CharField(max_length=50, verbose_name='Email')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='M', max_length=1, verbose_name='Sexo')),
                ('cedula', models.CharField(max_length=50, verbose_name='Cédula')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitokuApp.profile')),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitokuApp.especialidad')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
                'db_table': 'doctor',
                'ordering': ['apellido_paterno', '-apellido_materno'],
            },
        ),
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_paterno', models.CharField(max_length=20, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=20, verbose_name='Apellido Materno')),
                ('nombres', models.CharField(max_length=20, verbose_name='Nombres')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='F', max_length=1, verbose_name='Sexo')),
                ('cedula', models.CharField(max_length=60, verbose_name='Cédula')),
                ('telefonoPaciente', models.IntegerField(verbose_name='Teléfono')),
                ('emailPaciente', models.CharField(max_length=50, verbose_name='Email')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitokuApp.profile')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'paciente',
                'ordering': ['apellido_paterno', '-apellido_materno'],
            },
        ),
        migrations.CreateModel(
            name='citaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCita', models.DateField(verbose_name='Fecha de la Cita')),
                ('horaCita', models.TimeField(verbose_name='Hora de la Cita')),
                ('estadoCita', models.IntegerField(default=1, verbose_name='Estado de la Cita')),
                ('motivoCancelacion', models.CharField(blank=True, max_length=240, null=True, verbose_name='Motivo de Cancelación')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitokuApp.doctor')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitokuApp.paciente')),
            ],
            options={
                'verbose_name': 'Cita Médica',
                'verbose_name_plural': 'Citas Médicas',
                'db_table': 'citaMedica',
                'ordering': ['fechaCita', '-horaCita', '-estadoCita'],
            },
        ),
    ]
