# Generated by Django 5.1.1 on 2024-09-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitokuApp', '0002_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='telefonoPaciente',
            field=models.IntegerField(verbose_name='Teléfono'),
        ),
    ]
