# Generated by Django 5.1.1 on 2024-09-17 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitokuApp', '0002_especialidad_doctor_paciente_citamedica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='apellido_materno',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='apellido_paterno',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='emailPaciente',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='telefonoPaciente',
        ),
    ]
