# Generated by Django 5.1.1 on 2024-09-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitokuApp', '0003_alter_paciente_telefonopaciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cedula',
            field=models.CharField(max_length=60, verbose_name='Cédula'),
        ),
    ]
