# Generated by Django 5.1.1 on 2024-09-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitokuApp', '0005_especialidad_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='nombre',
            field=models.CharField(default='Sin Especialidad', max_length=30, verbose_name='Nombre de la Especialidad'),
        ),
    ]
