# Generated by Django 5.1.1 on 2024-09-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitokuApp', '0006_especialidad_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='anio_recebimiento',
            field=models.DateField(verbose_name='Año de Recebimiento'),
        ),
    ]
