# Generated by Django 5.1.1 on 2024-09-16 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitokuApp', '0007_alter_especialidad_anio_recebimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='citaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCita', models.DateField(verbose_name='Fecha de la Cita')),
                ('horaCita', models.TimeField(verbose_name='Hora de la Cita')),
                ('estadoCita', models.IntegerField(default=1, verbose_name='Estado de la Cita')),
                ('motivoCancelacion', models.CharField(max_length=240, verbose_name='Motivo de Cancelación')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitokuApp.doctor')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitokuApp.paciente')),
            ],
            options={
                'verbose_name': 'Cita Médica',
                'verbose_name_plural': 'Citas Médicas',
                'db_table': 'citaMedica',
                'ordering': ['fechaCita', '-horaCita', '-estadoCita'],
            },
        ),
    ]
