# Generated by Django 5.1.1 on 2024-09-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitokuApp', '0008_citamedica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citamedica',
            name='motivoCancelacion',
            field=models.CharField(max_length=240, null=True, verbose_name='Motivo de Cancelación'),
        ),
    ]
