# Generated by Django 5.1.1 on 2024-09-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitokuApp', '0009_alter_citamedica_motivocancelacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citamedica',
            name='motivoCancelacion',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Motivo de Cancelación'),
        ),
    ]
